name: "Sphinx Build"
on: 
- push
- pull_request

jobs:
  docs:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
#     - name: Install Prerequisites
#       run: |
#         sudo apt-get update
#         sudo apt-get upgrade
#         sudo apt-get install gcc --only-upgrade
#         sudo apt-get install -y python-dev python3-dev python3-pip
#         pip install "psutil==5.7.0"
#         pip3 install "psutil==5.7.0"
    - uses: ammaraskar/sphinx-action@master
      with:
        docs-folder: "docs/"
        pre-build-command: "pip install -U -r docs/requirements.txt"
        build-command: "sphinx-build -b html . _build"
    - run: "ls -Rp . && pwd"
    - name: Commit documentation changes
      run: |
        git clone https://github.com/minesh1291/ts-train.git --branch gh-pages --single-branch gh-pages
        cp -r docs/_build/* gh-pages/
        cd gh-pages
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "Update documentation" -a || true
        # The above command will fail if no changes were present, so we ignore
        # the return code.
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        branch: gh-pages
        directory: gh-pages
        github_token: ${{ secrets.GH_TOKEN }}
        
        
